### ISSUE TITLE
Earn coins - form validation

### ISSUE THREAD

**Issue by janhenrikfock** [neuefische/qcoins-mvp#11]
## Value statement - a requirement, not a solution
As a **(user** 
I should **not** be able to aern 0 coins, and still be able to proceed to the distribution page.

## Acceptance criteria
- [ ] Form Validation for input field. 0 not allowed.

## Tasks
- [ ] Form validation

## Size
small

**Comment by mpagels** [comment]
I'm doing this right now. If anybody want to help, be welcome. Pull request is coming ;-)
